server:
  port: 9880
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    username: root
    password: Bcbc963852
    url: jdbc:mysql://192.168.31.42:3306/amwpspot
    driver-class-name: com.mysql.jdbc.Driver
person:
  lastName: hello
  age: 18
  boss: false
  birth: 2017/12/12
  maps: {k1:v1,k2:12}
  lists:
    - lisi
    - zhaoliu
  dog:
    name: 小狗
    age: 12

mybatis:
  # 指定全局配置文件
#  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件的位置
  mapper-locations: classpath*:mybatis/*.xml
